HouseListingSystem/main/routes.py
from flask import render_template, redirect, url_for, request, Blueprint, flash
from HouseListingSystem import db
from flask_login import current_user
from HouseListingSystem.posts.models import House, Like, Images, City
from HouseListingSystem.posts.forms import SearchForm, FilterForm

main = Blueprint('main', __name__)


# passing search form to navbar in layout
@main.context_processor
def layout():
    form = SearchForm()
    cities = City.query.all()
    return dict(form=form, cities=cities)


@main.route('/')
@main.route('/home', methods=['GET', 'POST'])
def home():
    filter_form = FilterForm()
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))
    page = request.args.get('page', 1, type=int)
    results = (db.session.query(House).outerjoin(Like, House.house_id == Like.house_id).group_by(House.house_id).filter(House.user_id != current_user.user_id).order_by(db.func.count(Like.house_id).desc()))
    images = Images.query.all()
    if filter_form.validate_on_submit():

        if filter_form.validate_on_submit():
            if filter_form.post_type.data != '--':
                print(filter_form.post_type.data)
                results = results.filter(House.post_type == filter_form.post_type.data)
            if filter_form.bhk.data != '--':
                results = results.filter(House.bhk == filter_form.bhk.data)
            if filter_form.property_type.data != '--':
                results = results.filter(House.property_type == filter_form.property_type.data)

            if len(filter_form.max_value.data) != 0:
                results = results.filter(House.value <= filter_form.max_value.data)
            if len(filter_form.min_value.data) != 0:
                results = results.filter(House.value >= filter_form.min_value.data)
            # if filter_form.verified:
            #     results = results.filter(House.verified == True)
    results = results.paginate(page=page, per_page=3)
    return render_template('home.html', title='Home Page', images=images, results=results, filter_form=filter_form)

HouseListingSystem/posts/routes.py
from flask import render_template, redirect, flash, url_for, request, abort, Blueprint
from HouseListingSystem import db, messages
from HouseListingSystem.users.models import User, Notification
from HouseListingSystem.posts.models import House, Like, Interest, Images, City, Comment
from HouseListingSystem.posts.forms import (PostHouseForm, UpdateHouseStatusForm,
                                            SearchForm, FilterForm, CommentForm)
from flask_login import current_user, login_required
from HouseListingSystem.posts.utils import send_mail
import cloudinary.uploader
import cloudinary.api
posts = Blueprint('posts', __name__)

admin = User.query.filter_by(is_admin=True).first()


@posts.route('/rent-house/<string:post_type>', methods=['GET', 'POST'])
@login_required
def post_house(post_type):
    form = PostHouseForm()
    if form.validate_on_submit():
        house = House(post_type=post_type, user=current_user, city=form.city.data, locality=form.locality.data,
                      address=form.address.data, bhk=form.bhk.data,
                      property_type=form.property_type.data, value=form.value.data, area=form.area.data)
        db.session.add(house)
        db.session.flush()
        # create notification
        text = f"New house posted by user : {current_user.username}"
        notification = Notification(type='new user', text=text, user_id=admin.user_id)
        db.session.add(notification)
        house_id = house.house_id
        if form.house_image.data:
            images = request.files.getlist('house_image')
            for i in images:
                upload_result = cloudinary.uploader.upload(i)
                image_file = upload_result["secure_url"]
                img = Images(image_file=image_file, house_id=house_id)
                db.session.add(img)
        else:
            image_file = 'https://res.cloudinary.com/disha-joshi/image/upload/v1657129931/house_default_i4lpdi.jpg'
            img = Images(image_file=image_file, house_id=house_id)
            db.session.add(img)
        db.session.commit()
        flash(messages.post_added, 'success')
        return redirect(url_for('main.home'))
    return render_template('post_house.html', title=post_type + ' House', form=form, post_type=post_type)


@posts.route('/house-post/<int:house_id>', methods=['GET', 'POST'])
@login_required
def house_post(house_id):
    comment_form = CommentForm()
    house = House.query.get_or_404(house_id)
    images = Images.query.filter_by(house_id=house.house_id)
    similar_houses = House.query.filter(House.house_id != house.house_id, House.user != current_user, House.city == house.city, House.locality==house.locality,
                                        House.post_type==house.post_type, House.bhk==house.bhk).limit(2).all()
    images_all = Images.query.all()
    comments = Comment.query.filter_by(house_id=house.house_id).all()
    form = UpdateHouseStatusForm()
    if form.validate_on_submit():
        return redirect(url_for('posts.update_status', house_id=house.house_id, status=form.status.data, ))
    return render_template('house_post.html', house=house, images=images, form=form,
                           similar_houses=similar_houses, images_all=images_all, comment_form=comment_form, comments=comments)


@posts.route('/add-comment/<int:house_id>', methods=['GET', 'POST'])
@login_required
def add_comment(house_id):
    comment_form = CommentForm()
    if comment_form.validate_on_submit():
        comment = Comment(house_id=house_id, user_id=current_user.user_id,
                          comment_content=comment_form.comment_content.data)
        db.session.add(comment)
        db.session.commit()
        flash('Comment added')
    return redirect(url_for('posts.house_post', house_id=house_id))


@posts.route('/delete-comment/<int:comment_id>')
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    house_id = comment.house_id
    db.session.delete(comment)
    db.session.commit()
    flash('Comment deleted')
    return redirect(url_for('posts.house_post', house_id=house_id))


@posts.route('/update_status/<int:house_id>/<status>')
@login_required
def update_status(house_id, status):
    house = House.query.get_or_404(house_id)
    house.status = status
    db.session.commit()
    flash(messages.status_updated, 'success')
    return redirect(url_for('posts.house_post', house_id=house.house_id))


@posts.route('/house-post/<int:house_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(house_id):
    house = House.query.get_or_404(house_id)
    if house.user != current_user:
        abort(403)
    form = PostHouseForm(obj=house)
    images = Images.query.filter(Images.house_id == house.house_id,
                                 Images.image_file != 'https://res.cloudinary.com/disha-joshi/image/upload/v1657129931/house_default_i4lpdi.jpg').all()
    if form.validate_on_submit():
        form.populate_obj(house)
        if form.house_image.data:
            images = request.files.getlist('house_image')
            for i in images:
                upload_result = cloudinary.uploader.upload(i)
                image_file = upload_result["secure_url"]
                img = Images(image_file=image_file, house_id=house_id)
                db.session.add(img)
        db.session.add(house)
        db.session.commit()
        flash(messages.post_updated, 'success')
        return redirect(url_for('posts.house_post', house_id=house.house_id))
    return render_template('update_post.html', title='Update Post', form=form,images=images, legend='Update House')


# class Post(MethodView):
#     def _get_item(self, house_id):
#         return self.House.query.get_or_404(house_id)
#
#     def get(self, house_id):
#         user = self._get_item(house_id)
#         return jsonify(item.to_json())


@posts.route('/delete-image/<int:image_id>')
@login_required
def delete_image(image_id):
    image = Images.query.get_or_404(image_id)
    house_id = image.house_id
    db.session.delete(image)
    db.session.commit()
    flash('Image deleted', 'warning')
    return redirect(url_for('posts.update_post', house_id=house_id))


@posts.route('/house-post/<int:house_id>/delete')
@login_required
def delete_post(house_id):
    house = House.query.get_or_404(house_id)
    db.session.delete(house)
    db.session.commit()
    flash(messages.post_deleted, 'success')
    return redirect(url_for('users.my_posts'))


# admin functions

@posts.route('/verified-posts')
@login_required
def verified_posts():
    if not current_user.is_admin:
        abort(403)
    else:
        page = request.args.get('page', 1, type=int)
        results = House.query.filter_by(verified=True).paginate(page=page, per_page=3)
        return render_template('posts_list.html', title='Verified Posts', results=results,
                               function='posts.verified_posts')


@posts.route('/unverified-posts')
@login_required
def unverified_posts():
    if not current_user.is_admin:
        abort(403)
    else:
        page = request.args.get('page', 1, type=int)
        results = House.query.filter_by(verified=False).paginate(page=page, per_page=3)
        return render_template('posts_list.html', title='Unverified Posts', results=results,
                               function='posts.unverified_posts')


@posts.route('/post-detail/<int:house_id>')
@login_required
def post_detail(house_id):
    if not current_user.is_admin:
        abort(403)
    house = House.query.get_or_404(house_id)
    images = Images.query.filter_by(house_id=house.house_id)
    return render_template('post_detail.html', title='Post Detail', house=house, images=images)


@posts.route('/verify-post/<int:house_id>')
@login_required
def verify_post(house_id):
    if not current_user.is_admin:
        abort(403)
    house = House.query.get_or_404(house_id)
    house.verified = True
    db.session.commit()
    flash(messages.verified_post, 'success')
    return redirect(url_for('posts.post_detail', house_id=house.house_id))


@posts.route('/like-post/<int:house_id>', methods=['GET'])
@login_required
def like_post(house_id):
    house = House.query.get_or_404(house_id)
    like = Like.query.filter_by(user_id=current_user.user_id, house_id=house.house_id).first()
    if like:
        db.session.delete(like)
        db.session.commit()
    else:
        like = Like(user_id=current_user.user_id, house_id=house.house_id)
        db.session.add(like)
        db.session.commit()
    return redirect(url_for('main.home'))


# passing search form to navbar in layout
@posts.context_processor
def layout():
    form = SearchForm()
    cities = City.query.all()
    return dict(form=form, cities=cities)


@posts.route('/searched-results', methods=['POST', 'GET'])
@login_required
def searched_results():
    form = SearchForm()
    filter_form = FilterForm()
    if form.validate_on_submit():
        searched_word = form.search.data
        results = House.query.filter(House.user != current_user, (House.city.ilike('%'+searched_word+'%')) |
                                     (House.locality.ilike('%'+searched_word+'%')) | (House.property_type.ilike('%'+searched_word+'%')))
        images = Images.query.all()

        return render_template('searched_results.html', form=form, filter_form=filter_form,
                               searched_word=searched_word, results=results, images=images)

    return render_template('searched_results.html', form=form, filter_form=filter_form)


@posts.route('/filtered-searched-results/<string:searched_word>', methods=['POST', 'GET'])
@login_required
def filtered_results(searched_word):
    filter_form = FilterForm()
    kwargs = {}
    results = House.query.filter_by(**kwargs).filter(House.user != current_user)
    if filter_form.validate_on_submit():
        if filter_form.post_type.data != '--':
            kwargs['post_type'] = filter_form.post_type.data
        if filter_form.bhk.data != '--':

HouseListingSystem/templates/admin_panel.html
{% extends "layout.html" %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
            <div class="admin-sidebar">
                <div class="border-end bg-white" id="sidebar-wrapper">
                    <div class="sidebar-heading border-bottom bg-light">Admin Functions</div>
                    <div class="list-group list-group-flush">
                        <a class="list-group-item list-group-item-action list-group-item-light p-3"
                           href="{{ url_for('users.verified_users') }}">Verified Users</a>
                        <a class="list-group-item list-group-item-action list-group-item-light p-3"
                           href="{{ url_for('users.unverified_users') }}">Unverified Users</a>
                        <a class="list-group-item list-group-item-action list-group-item-light p-3"
                           href="{{ url_for('posts.verified_posts') }}">Verified Posts</a>
                        <a class="list-group-item list-group-item-action list-group-item-light p-3"
                           href="{{ url_for('posts.unverified_posts') }}">Unverified Posts</a>
                        <!--                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Profile</a>-->
                        <!--                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Status</a>-->
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            {%block admincontent%}{% endblock %}
        </div>
    </div>

</div>


{% endblock content %}

HouseListingSystem/templates/chat.html
{% extends "chat_rooms.html" %}
{% block chat %}
Message Window
<div id="chat-section">
    {% for m in msgs %}
    <p>
        <span>{{m.user.username}}  {{m.time_stamp}}</span>
        <br>
        {{ m.message }}
    </p>
    {% endfor %}
</div>
<div class="input-area">
    <input type="text" id="message_input" placeholder="Type Message..." autocomplete="off" class="form-control">
    <button type="button" id="send_message" class="btn btn-sm btn-outline-info">Send</button>
</div>

<script type="text/javascript">
    const username = `{{ username }}`
    const room = `{{room_id}}`
</script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"
        integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA=="
        crossorigin="anonymous"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/socketio.js') }}">

</script>
{% endblock chat %}

HouseListingSystem/templates/home.html
{% extends "layout.html" %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            <form method="POST"
                  novalidate>
                {{ filter_form.hidden_tag() }}
                <fieldset class="form-group">
                    {{ filter_form.post_type.label }}
                    {% if filter_form.post_type.errors %}
                    {{ filter_form.post_type(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in filter_form.post_type.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ filter_form.post_type(class="form-control") }}
                    {% endif %}
                    <br>
                    {{ filter_form.bhk.label }}
                    {% if filter_form.bhk.errors %}
                    {{ filter_form.bhk(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in filter_form.bhk.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ filter_form.bhk(class="form-control") }}
                    {% endif %}

                    <br>
                    {{ filter_form.min_value.label }}
                    {% if filter_form.min_value.errors %}
                    {{ filter_form.min_value(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in filter_form.min_value.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ filter_form.min_value(class="form-control") }}
                    {% endif %}
                    <br>
                    {{ filter_form.max_value.label }}
                    {% if filter_form.max_value.errors %}
                    {{ filter_form.max_value(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in filter_form.max_value.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ filter_form.max_value(class="form-control") }}
                    {% endif %}
                    <br>
                    {{ filter_form.property_type.label }}
                    {% if filter_form.property_type.errors %}
                    {{ filter_form.property_type(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in filter_form.property_type.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ filter_form.property_type(class="form-control") }}
                    {% endif %}
                    <br>
                    {{ filter_form.verified.label }}
                    {{ filter_form.verified }}
                </fieldset>
                <br>
                <div>
                    {{ filter_form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
        </div>
        <div class="col-md-8">
            {% for house in results.items %}
            <div class="list-group list-group d-grid gap-2 border-0 w-auto posts">

                <label class="list-group-item rounded-3 py-3">
                    <div class="article-metadata">
                        <img src="{{house.user.profile}}" class="user-profile-in-post">
                        <small>Posted by {{ house.user.username }} on {{ house.date_posted.strftime('%Y-%m-%d')
                            }}</small>
                        <span class="like-icon" style="float : right">{{ house.like|length }}
                    {% if current_user.user_id in house.like|map(attribute="user_id")|list %}
                    <a href="{{url_for('posts.like_post', house_id=house.house_id)}}"><i
                            class="bi bi-hand-thumbs-up-fill"></i></a>
                    {% else %}
                    <a href="{{url_for('posts.like_post', house_id=house.house_id)}}"><i
                            class="bi bi-hand-thumbs-up"></i></a>
                    {% endif %}
                    </span>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div id="demo" class="carousel slide" data-bs-ride="carousel">
                                <!-- The slideshow/carousel -->

                                <div class="carousel-inner">
                                    {% for img in images %}
                                    {% if img.house_id == house.house_id %}
                                    <div class="carousel-item active">
                                        <img src="{{img.image_file}}" class="d-block home-my-posts-house-img">
                                    </div>
                                    {% endif %}
                                    {% endfor %}
                                </div>

                                <!-- Left and right controls/icons -->
                                <button class="carousel-control-prev" type="button" data-bs-target="#demo"
                                        data-bs-slide="prev">
                                    <span class="carousel-control-prev-icon"></span>
                                </button>
                                <button class="carousel-control-next" type="button" data-bs-target="#demo"
                                        data-bs-slide="next">
                                    <span class="carousel-control-next-icon"></span>
                                </button>
                            </div>

                        </div>
                        <div class="col-md-8">
                            <h5>{{ house.bhk }} BHK {{ house.property_type }} for {{ house.post_type }} in {{
                                house.locality }}, {{ house.city }}</h5>
                            {% if house.post_type == 'rent' %}
                            <p>Rent Per Month : {{ house.value }}</p>
                            {% else %}
                            <p>Price : {{ house.value }}</p>
                            {% endif %}
                            <a href="{{ url_for('posts.house_post', house_id=house.house_id) }}" class="btn btn-info">View
                                More</a>

                        </div>
                    </div>
                </label>
            </div>
            <br>

            {% endfor %}
            {% for page_num in results.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
            {% if results.page == page_num %}
            <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% else %}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
            {% else %}
            ...
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

HouseListingSystem/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>House Selling Renting System</title>
    {% endif %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js">
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.js">
    </script>

    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/ui-lightness/jquery-ui.css"
          rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/custom.css')}}">
</head>

<body>

<nav class="py-2 bg-light border-bottom">
    <div class="container d-flex flex-wrap">
        <ul class="nav me-auto">
            <li class="nav-item"><a href="{{ url_for('main.home') }}" class="nav-link link-dark px-2 active"
                                    aria-current="page">Home</a></li>

            {% if current_user.is_authenticated %}
            <div class="dropdown">
                <button type="button" class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown">
                    Post Property
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{{ url_for('posts.post_house', post_type='sell') }}">For Sell</a>
                    </li>
                    <li><a class="dropdown-item" href="{{ url_for('posts.post_house', post_type='rent') }}">For Rent</a>
                    </li>
                </ul>
            </div>
            <li class="nav-item"><a href="{{ url_for('users.show_notifications') }}" class="nav-link link-dark px-2 active"
                                    aria-current="page">Notifications</a></li>
            {% endif %}
        </ul>

        <ul class="nav">
            {% if current_user.is_authenticated %}
            {% if current_user.is_admin == True %}
            <li class="nav-item"><a href="{{ url_for('users.admin_panel') }}" class="nav-link link-dark px-2">Admin
                Panel</a></li>
            {% endif %}
            <li class="nav-item"><a href="{{ url_for('users.chat_rooms') }}" class="nav-link link-dark px-2">Messages
            </a></li>
            <div class="dropdown">
                <button type="button" class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown">
                    Hi..{{current_user.username}}
                </button>

                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{{url_for('users.view_account')}}">View Account</a></li>
                    <li><a class="dropdown-item" href="{{url_for('users.my_favourites')}}">Favourites</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('users.my_posts') }}">Posts</a></li>
                </ul>
            </div>
            <li class="nav-item"><a href="{{ url_for('users.logout')}}" class="nav-link link-dark px-2">Log Out </a>
            </li>
            {% else %}
            <li class="nav-item"><a href="{{ url_for('users.login') }}" class="nav-link link-dark px-2">Login</a></li>
            <li class="nav-item"><a href="{{ url_for('users.register') }}" class="nav-link link-dark px-2">Register</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
{% if current_user.is_authenticated %}
<header class="py-3 mb-4 border-bottom">
    <div class="container d-flex flex-wrap justify-content-center">
        <form class="col-12 col-lg-auto mb-3 mb-lg-0" role="search" method="POST"
              action="{{ url_for('posts.searched_results') }}">
            {{ form.hidden_tag() }}
            <input class="form-control" type="search" id="tags" placeholder="Search City" name="search">
            <button class="btn btn-info" type="submit" name="submit">Search</button>
        </form>
    </div>
</header>
{% endif %}
{% with messages = get_flashed_messages(with_categories=true ) %}
{% if messages %}
{% for category,message in messages %}
<div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
</div>
{% endfor %}
{% endif %}
{% endwith %}
{%block content%}{% endblock %}
<!--JS CDN-->

<script>
  $( function() {
    var availableTags = [
        {% for city in cities %}
            "{{city.city_name}}",
        {% endfor %}
    ];
    $( "#tags" ).autocomplete({
      source: availableTags
    });
  } );

</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

HouseListingSystem/templates/my_favourites.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="col-md-8">
        {% for house in results.items %}
        <div class="list-group list-group d-grid gap-2 border-0 w-auto posts">

            <label class="list-group-item rounded-3 py-3">
                <div class="article-metadata">
                    <img src="{{house.user.profile}}" class="user-profile-in-post">
                    <small>Posted by {{ house.user.username }} on {{ house.date_posted.strftime('%Y-%m-%d') }}</small>
                    <span class="like-icon" style="float : right">{{ house.like|length }}
                    {% if current_user.user_id in house.like|map(attribute="user_id")|list %}
                    <a href="{{url_for('posts.like_post', house_id=house.house_id)}}"><i
                            class="bi bi-hand-thumbs-up-fill"></i></a>
                    {% else %}
                    <a href="{{url_for('posts.like_post', house_id=house.house_id)}}"><i
                            class="bi bi-hand-thumbs-up"></i></a>
                    {% endif %}
                    </span>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div id="demo" class="carousel slide" data-bs-ride="carousel">
                            <!-- The slideshow/carousel -->

                            <div class="carousel-inner">
                                {% for img in images %}
                                {% if img.house_id == house.house_id %}
                                <div class="carousel-item active">
                                    <img src="{{img.image_file}}" class="d-block home-my-posts-house-img">
                                </div>
                                {% endif %}
                                {% endfor %}
                            </div>

                            <!-- Left and right controls/icons -->
                            <button class="carousel-control-prev" type="button" data-bs-target="#demo"
                                    data-bs-slide="prev">
                                <span class="carousel-control-prev-icon"></span>
                            </button>
                            <button class="carousel-control-next" type="button" data-bs-target="#demo"
                                    data-bs-slide="next">
                                <span class="carousel-control-next-icon"></span>
                            </button>
                        </div>

                    </div>
                    <div class="col-md-8">
                        <h5>{{ house.bhk }} BHK {{ house.property_type }} for {{ house.post_type }} in {{ house.locality
                            }}, {{ house.city }}</h5>
                        {% if house.post_type == 'rent' %}
                        <p>Rent Per Month : {{ house.value }}</p>
                        {% else %}
                        <p>Price : {{ house.value }}</p>
                        {% endif %}
                        <a href="{{ url_for('posts.house_post', house_id=house.house_id) }}" class="btn btn-info">View
                            More</a>

                    </div>
                </div>
            </label>
        </div>
        <br>
        {% endfor %}
    </div>
    {% for page_num in results.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
    {% if results.page == page_num %}
    <a class="btn btn-info mb-4" href="{{ url_for('users.my_favourites', page=page_num) }}">{{ page_num }}</a>
    {% else %}
    <a class="btn btn-outline-info mb-4" href="{{ url_for('users.my_favourites', page=page_num) }}">{{ page_num }}</a>
    {% endif %}
    {% else %}
    ...
    {% endif %}
    {% endfor %}
</div>
{% endblock content %}